# Generated by Django 2.2.5 on 2019-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190908_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
